// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_zGexlcWVoIEyjdwGJHOnkIaUG3fjR-c',
    appId: '1:412744498113:web:17e0daa06312e7de2f8d40',
    messagingSenderId: '412744498113',
    projectId: 'child-rights-international',
    authDomain: 'child-rights-international.firebaseapp.com',
    storageBucket: 'child-rights-international.appspot.com',
    measurementId: 'G-EJRHFFMYSX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2TOfIgG3YfTjU5sZkuqBl6t7KmgT9gU',
    appId: '1:412744498113:android:3dbe0c95ade7d9e52f8d40',
    messagingSenderId: '412744498113',
    projectId: 'child-rights-international',
    storageBucket: 'child-rights-international.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1FgcAluYid0Zzy4ULr5HsQJmFyIqQiA',
    appId: '1:412744498113:ios:d891ac39ea3bf0352f8d40',
    messagingSenderId: '412744498113',
    projectId: 'child-rights-international',
    storageBucket: 'child-rights-international.appspot.com',
    iosClientId: '412744498113-8nt8ltjgegc9es24r2ovlnj5runt9p0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.safekid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm1FgcAluYid0Zzy4ULr5HsQJmFyIqQiA',
    appId: '1:412744498113:ios:d891ac39ea3bf0352f8d40',
    messagingSenderId: '412744498113',
    projectId: 'child-rights-international',
    storageBucket: 'child-rights-international.appspot.com',
    iosClientId: '412744498113-8nt8ltjgegc9es24r2ovlnj5runt9p0r.apps.googleusercontent.com',
    iosBundleId: 'com.example.safekid',
  );
}
