// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy2TOfIgG3YfTjU5sZkuqBl6t7KmgT9gU',
    appId: '1:412744498113:android:be4706638d77758e2f8d40',
    messagingSenderId: '412744498113',
    projectId: 'child-rights-international',
    storageBucket: 'child-rights-international.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm1FgcAluYid0Zzy4ULr5HsQJmFyIqQiA',
    appId: '1:412744498113:ios:7ec525a83b9827772f8d40',
    messagingSenderId: '412744498113',
    projectId: 'child-rights-international',
    storageBucket: 'child-rights-international.appspot.com',
    androidClientId: '412744498113-9i56706q3mfav8bdmpbd1efjaehlgnar.apps.googleusercontent.com',
    iosClientId: '412744498113-0ov33m24j4ud90mp1jjs4b222oohumuj.apps.googleusercontent.com',
    iosBundleId: 'com.cri.safekidGh',
  );
}
